name: gen-tiktok-compilation
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Install all necessary packages
        run: pip install  youtube_dl ffmpeg 
      - name: Run the scraping script
        run: bash gen-tiktok-compilation.sh 5

      # 更新仓库
      - name: Update repo
        run: |
          git add .
          git commit -m "auto update gen-tiktok-compilation"
          git pull
          git push -u origin main
