name: keep-heroku-alive
on:
  schedule:
    - cron: '*/25 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our tiktoka API route
        run: |
          curl --request GET \
          --url 'https://tiktoka.herokuapp.com/' 
      - name: Call our myowndaily route
        run: |
          curl --request GET \
          --url 'https://myowndaily.herokuapp.com/'      
      - name: Call our link detection route
        run: |
          curl --request GET \
          --url 'https://links-detection-shopconna.herokuapp.com/'               


