name: keep-heroku-alive
on:
  schedule:
    - cron: '*/25 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://tiktoka.herokuapp.com/' 
